[package]
name = "telegram-dice-maestro-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.2.1", features = ["derive", "env"] }
# itertools = "0.10.5"
lazy_static = "1.4.0"
log = "0.4"
pretty_env_logger = "0.4"
rand = "0.8.5"
regex = "1.7.3"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
# serde = { version = "1.0.159", features = ["derive"] }
# serde_json = "1.0.95"
teloxide = { version = "0.12", features = ["macros", "cache-me", "throttle"] }
tempfile = "3.5.0"
thiserror = "1.0.40"
# thiserror = "1.0.40"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
