# For GitHub Actions build
FROM cgr.dev/chainguard/static:latest

LABEL org.opencontainers.image.source=https://github.com/lawliet89/telegram-dice-maestro-oxide
LABEL org.opencontainers.image.licenses=Apache-2.0

COPY targets/${TARGETPLATFORM}/telegram-dice-maestro-oxide /

CMD ["/telegram-dice-maestro-oxide"]
