name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: armv7-unknown-linux-gnueabihf
          - target: x86_64-apple-darwin
          - target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release
      # - name: Compile
      #   id: compile
      #   uses: rust-build/rust-build.action@v1.4.3
      #   with:
      #     RUSTTARGET: ${{ matrix.target }}
      #     # ARCHIVE_TYPES: ${{ matrix.archive }}
      #     UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            target/release/
